name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      
      - name: Start APIs Rest & GraphQL
        run: npm run start:all

      - name: Wait for APIs to be ready
        run: sleep 8
      
      - name: Create .env
        run: |
          echo "BASE_URL_REST=${{ secrets.BASE_URL_REST }}" >> .env
          echo "BASE_URL_GRAPHQL=${{ secrets.BASE_URL_GRAPHQL }}" >> .env
      
      - name: Run Rest API tests via HTTP
        run: npm run test-rest-external
      
      - name: Run GraphQL API tests via HTTP
        run: npm test